spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OshadhiVimarsha/Library-Configurations.git
          search-paths: platform, services
          default-label: master
        native:
          search-locations:
            - classpath:/configurations
            - classpath:/configurations/platform
            - classpath:/configurations/services

server:
  port: 9000